# 1. Node.js 이미지를 베이스로 사용
FROM node:18

# 2. 컨테이너 내부 작업 디렉토리를 설정
WORKDIR /usr/src/app

# 3. package.json과 package-lock.json만 복사 (의존성 캐싱 최적화)
COPY ./app/package*.json ./app/

# 4. 의존성 설치
RUN npm install --prefix ./app

# 5. React 애플리케이션 코드 복사
COPY ./app ./app

# 6. React 애플리케이션 빌드
RUN npm run build --prefix ./app

# 7. HTTP 서버 설치
RUN npm install -g serve

# 8. 컨테이너 포트 노출
EXPOSE 3000

# 9. 빌드된 애플리케이션 실행
CMD ["serve", "-s", "app/build"]
