# 1. Node.js 이미지를 베이스로 사용
FROM node:18

# 2. 컨테이너 내 작업 디렉토리를 설정
WORKDIR /usr/src/app

# 3. package.json과 package-lock.json만 복사 (의존성 캐싱 최적화)
COPY ./app/package*.json ./

# 4. 종속성 설치
RUN npm install

# 5. React 애플리케이션 코드를 컨테이너에 복사
COPY ./app ./

# 6. 빌드 React 앱
RUN npm run build

# 7. 컨테이너가 사용하는 포트 설정
EXPOSE 3000

# 8. React 앱을 실행하는 간단한 HTTP 서버 설치
RUN npm install -g serve

# 9. 애플리케이션 실행
CMD ["serve", "-s", "build"]